---

- name: Ubuntu Uzerine Apache Kurma
  hosts: webservers
  gather_facts: false
  remote_user: ubuntu
  become: true

  tasks:
    - name: ensure apache is at the latest version
      apt: name=apache2 update_cache=yes state=latest

    - name: make sure apache is running
      service: name=apache2 state=started


# Komut Çalıştırma sekli bu kez -i <çalıştığın dizindeki dosya adı> şeklinde yapılmalı ki inventory dosyasına bakabilsin
# ansible-playbook -i hosts install-apache-package.yml

...